version: '3.4'

services:
  postgresql-proxy:
    image: postgresql-proxy
    build:
      context: .
      dockerfile: Dockerfile
      target: build-deps
    ports:
      - 8890:8890
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    volumes:
      - test-postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword

volumes:
  test-postgres-db: