version: '3.4'

services:
  pg-fort:
    image: pg-fort:devcontainer
    build:
      dockerfile: Dockerfile
      target: build-deps
    volumes:
      - .:/workspace:cached
      - bashhistory:/commandhistory
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
    bashhistory:
